# builds an HTML documentation page from the README
doc:
	asciidoctor README.adoc -o doc.html

# builds the site for development (including drafts)
dev: clean
	hugo --buildDrafts

# builds the site for production (minimized)
prod: clean
	hugo --minify

# serves the hugo server
serve: clean
	hugo --buildDrafts serve

# cleans the public and resources directories
clean:
	[ -d './public/' ] && rm -r './public' || true
	[ -d './resources/' ] && rm -r './resources' || true
